name: beam-sqlite-demo
version: 0.1.0.0
github: "githubuser/beam-sqlite-demo"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/beam-sqlite-demo#readme>

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - lens
  - lens-aeson
  - mtl
  - text
  - time
  - yaml
  - conduit
  - http-client
  - http-types
  - path
  - stm
  - vector
  - modern-uri
  - SHA
  - servant-server
  - servant-client
  - servant
  - wai
  - warp
  - network
  - monad-parallel
  - unix
  - filepath
  - extra
  - exceptions
  - monad-control
  - transformers
  - megaparsec
  - async
  - beam-migrate
  - beam-core
  - beam-sqlite
  - sqlite-simple
  - uuid

library:
  source-dirs: src

executables:
  beam-sqlite-demo-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - beam-sqlite-demo
tests:
  beam-sqlite-demo-test:
    main: Driver.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - beam-sqlite-demo
      - tasty
      - tasty-hunit
      - tasty-golden
      - tasty-quickcheck
      - quickcheck-instances
      - tasty-smallcheck
      - generic-random
      - uuid
      - hspec-wai
      - hspec-wai-json
